config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :sports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  def index
    if params[:query].present?
      @sports = Sport.where(name: params[:query].capitalize)
    else
      @sports = Sport.all
    end
  end

  def show
    @sport = Sport.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
 <div>
    <h1>Move</h1>
    <h2>If you like <span id="typed"></span></h2>
  </div>
  <h3>What do you want to do today ?</h3>
    <%= form_with url: sports_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Sports" %>
        <%= submit_tag "Go", class: "btn"%>
    <% end %>
  <div class="link">
<%= link_to ">> All the sports", sports_path %>
  </div>

app/views/sports/index.html.erb
<div class="index">
<h1>Sports</h1>
</div>
<div class="container">
<% @sports.each do |sport| %>
  <%= link_to sport_path(sport) do %>
   <div class="card">
      <p><%= sport.name %></p>
      <p><%= sport.location %></p>
      <p><%= sport.difficulty %></p>
      <p><%= sport.level %></p>
      <p><%= sport.distance %></p>
      <div class="card-img">
        <p><%= image_tag sport.image_url %></p>
      </div>

    </div>
  <% end %>
<% end  %>
</div>

app/views/sports/show.html.erb
<div class="back">
<%= link_to "<< Back", sports_path %>
</div>
<div class="show">
  <div class="titlecards">
  <p><%= @sport.name %></p>
  <p><%= @sport.location %></p>
  <p><%= @sport.difficulty %></p>
  <p><%= @sport.level %></p>
  <p><%= @sport.distance %></p>
  </div>
  <div class="picture">
    <p><%= image_tag @sport.image_url %></p>
  </div>
    </div>
  </div>
</div>